services:
  - name: prediction_engine_practice
    type: web
    env: python=3.11
    buildCommand: pip install -r requirements.txt
    startcommand: uvicorn prediction_engine_practice:app --host 0.0.0.0 --port $PORT
